---
- name: Tuning kernel for linux.
  lineinfile: 
    dest: "{{ security_sysctl_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop  :
    - regexp: "^tcp_keepalive_time"
      line: "{{ tcp_keepalive_time }}"
    - regexp: "^route_gc_timeout"
      line: "{{ route_gc_timeout }}"
    - regexp: "^ip_local_port_range"
      line: "{{ ip_local_port_range }}"
    - regexp: "^tcp_syn_retries"
      line: "{{ tcp_syn_retries }}"
    - regexp: "^tcp_synack_retries"
      line: "{{ tcp_synack_retries }}"
    - regexp: "^tcp_max_syn_backlog"
      line: "{{ tcp_max_syn_backlog }}"
    - regexp: "^netdev_max_backlog"
      line: "{{ netdev_max_backlog }}"
    - regexp: "^core_somaxconn"
      line: "{{ core_somaxconn }}"
    - regexp: "^tcp_mem"
      line: "{{ tcp_mem }}"
    - regexp: "^tcp_syncookies"
      line: "{{ tcp_syncookies }}"
    - regexp: "^net_core_rmem_max"
      line: "{{ net_core_rmem_max }}"
    - regexp: "^net_core_wmem_max"
      line: "{{ net_core_wmem_max }}"
    - regexp: "^net_ipv4_tcp_rmem"
      line: "{{ net_ipv4_tcp_rmem }}"
    - regexp: "^net_core_netdev_max_backlog"
      line: "{{ net_core_netdev_max_backlog }}"
    - regexp: "^net_ipv4_tcp_moderate_rcvbuf"
      line: "{{ net_ipv4_tcp_moderate_rcvbuf }}"
    - regexp: "^net_ipv4_tcp_no_metrics_save"
      line: "{{ net_ipv4_tcp_no_metrics_save }}"
    - regexp: "^net_ipv4_tcp_congestion_control"
      line: "{{ net_ipv4_tcp_congestion_control }}"
    - regexp: "^net_ipv4_tcp_mtu_probing"
      line: "{{ net_ipv4_tcp_mtu_probing }}"       
    - regexp: "^tcp_max_tw_buckets"
      line: "{{ tcp_max_tw_buckets }}"
    - regexp: "^tcp_tw_recycle"
      line: "{{ tcp_tw_recycle }}"    
    - regexp: "^tcp_tw_reuse"
      line: "{{ tcp_tw_reuse }}"    
    - regexp: "^udp_wmem_min"
      line: "{{ udp_wmem_min }}"      
    - regexp: "^tcp_mem"
      line: "{{ tcp_mem }}" 
    - regexp: "^udp_mem"
      line: "{{ udp_mem }}"   
    - regexp: "^optmem_max"
      line: "{{ optmem_max }}"    
    - regexp: "^tcp_fin_timeout"
      line: "{{ tcp_fin_timeout }}"                                                 
  notify: sysctl -p